### ISSUE TITLE
Salus failing after recent release

### ISSUE THREAD

**Issue by Piccirello** [federacy/scan-action#4]
Around 2 weeks ago, all scan-action runs started failing. It appears related to the release of either Salus [2.10.15](https://github.com/coinbase/salus/releases/tag/2.10.15) or [2.10.16](https://github.com/coinbase/salus/releases/tag/2.10.16). The GitHub Action displays this error:

```
bundler: failed to load command: /home/bin/salus (/home/bin/salus)
Errno::ENOENT: No such file or directory - bandit
  /usr/local/lib/ruby/2.7.0/open3.rb:213:in `spawn'
  /usr/local/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
  /usr/local/lib/ruby/2.7.0/open3.rb:101:in `popen3'
  /usr/local/lib/ruby/2.7.0/open3.rb:281:in `capture3'
  /home/lib/salus/scanners/base.rb:100:in `run_shell'
  /home/lib/salus/scanners/bandit.rb:66:in `version'
  /home/lib/salus/scanners/base.rb:25:in `initialize'
  /home/lib/salus/processor.rb:76:in `new'
  /home/lib/salus/processor.rb:76:in `block (2 levels) in scan_project'
  /home/lib/salus/processor.rb:73:in `each'
  /home/lib/salus/processor.rb:73:in `block in scan_project'
  /home/lib/salus/report.rb:38:in `record'
  /home/lib/salus/processor.rb:68:in `scan_project'
  /home/lib/salus.rb:46:in `scan'
  /home/lib/salus/cli.rb:33:in `scan'
  /home/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  /home/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  /home/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  /home/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
  /home/bin/salus:8:in `<top (required)>'
```

**Comment by jsulinski** [comment]
Hey @Piccirello, I wasn't aware anyone was using this. Great to see! 

It looks like the Docker changes in Salus in version 2.10.15 are causing an issue in Github Actions (but not CircleCI, strangely). 

I've gone ahead and shipped a hotfix to the Github Action that pegs Salus at 2.10.14. Let me know if this helps. 

https://github.com/marketplace/actions/federacy-salus-security-scan?version=0.1.1-hotfix

**Comment by Piccirello** [comment]
We've been using this action for almost a year now and it's provided a ton of value. Major thanks for building and sharing it! Oddly enough, `0.1.1-hotfix` doesn't seem to have helped. I'm still getting the following error. I also tried switching our runner (code below) from `ubuntu-latest` to `ubuntu-18.04` in case a recent GitHub switch to `ubuntu-20.04` was the cause, but no dice.

```
Run federacy/scan-action@0.1.1-hotfix
  with:
    active_scanners: all
    enforced_scanners: all
    report_uri: file://../salus-report.json
    report_format: json
    report_verbosity: true
  env:
    SALUS_CONFIGURATION: file://salus-config.yaml
/usr/bin/docker run --name e4fa314b44dab1423ca4600fa2a5d374a7_a9f4ef --label 5588e4 --workdir /github/workspace --rm -e SALUS_CONFIGURATION -e INPUT_ACTIVE_SCANNERS -e INPUT_ENFORCED_SCANNERS -e INPUT_REPORT_URI -e INPUT_REPORT_FORMAT -e INPUT_REPORT_VERBOSITY -e INPUT_CONFIGURATION_FILE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/server/server":"/github/workspace" 5588e4:fa314b44dab1423ca4600fa2a5d374a7

config_version: 1
active_scanners: all
enforced_scanners: all

custom_info:
  sha1: [REDACTED]
  reponame: [REDACTED]
  ref: [REDACTED]
  ci_username: Piccirello
  github_action: federacyscan-action
  github_workflow: Scanners
  github_event_name: push
  github_event_path: /github/workflow/event.json
  github_workspace: /github/workspace
  github_head_ref: 
  github_base_ref: 
  github_home: /github/home

reports:
  - uri: file://../salus-report.json
    format: json
    verbose: true
bundler: failed to load command: /home/bin/salus (/home/bin/salus)
Errno::ENOENT: No such file or directory - bandit
  /usr/local/lib/ruby/2.7.0/open3.rb:213:in `spawn'
  /usr/local/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
  /usr/local/lib/ruby/2.7.0/open3.rb:101:in `popen3'
  /usr/local/lib/ruby/2.7.0/open3.rb:281:in `capture3'
  /home/lib/salus/scanners/base.rb:100:in `run_shell'
  /home/lib/salus/scanners/bandit.rb:66:in `version'
  /home/lib/salus/scanners/base.rb:25:in `initialize'
  /home/lib/salus/processor.rb:76:in `new'
  /home/lib/salus/processor.rb:76:in `block (2 levels) in scan_project'
  /home/lib/salus/processor.rb:73:in `each'
  /home/lib/salus/processor.rb:73:in `block in scan_project'
  /home/lib/salus/report.rb:38:in `record'
  /home/lib/salus/processor.rb:68:in `scan_project'
  /home/lib/salus.rb:46:in `scan'
  /home/lib/salus/cli.rb:33:in `scan'
  /home/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  /home/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  /home/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  /home/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
  /home/bin/salus:8:in `<top (required)>'
[INFORMATIONAL: 2021-02-24 20:26:36 +0000]: Salus is running.
```

Here's my github workflow, in case it's helpful:

```yaml
name: Scanner
on: [push]
jobs:
  salus_security:
    runs-on: ubuntu-latest
    name: Salus
    steps:
      - uses: actions/checkout@v2
      - name: Salus Scan
        id: salus_scan
        uses: federacy/scan-action@0.1.1-hotfix
        env:
          SALUS_CONFIGURATION: "file://salus-config.yaml"
      - uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Salus report
          path: ./salus-report.txt
```

**Comment by jsulinski** [comment]
This is really awesome to hear! Glad it has provided some value. 

Can you try running the Action again? I accidentally botched the release last night after testing another version. I just pushed a new release (with the same name) and tested on my side.

**Comment by Piccirello** [comment]
Tried again with the hotfix release and it's working great! Thanks so much for looking into this and the quick fix.

**Comment by jsresearch** [comment]
@Piccirello Just released a proper fix if you want to bump to 0.1.2. This will ensure you get new versions as Salus releases them.

**Comment by jsulinski** [comment]
@Piccirello Just released a proper fix if you want to bump to 0.1.2. This will ensure you get new versions as Salus releases them.

**Comment by Piccirello** [comment]
Confirmed v0.1.2 is working great. Thanks @jsulinski!

**Comment by jsulinski** [comment]
@Piccirello Just wanted to give you a heads up that I pushed a new release over the 0.1.2 tag along with some documentation updates in 0.1.3. Apologies if you got a lot of alerts, was having issues with the Github Actions marketplace. Please let me know if you have any issues.
